/**
 * Forgeonix CRM — demo seed data (Phase 1).
 *
 * Realistic in-memory dataset used when demo mode is on. Dates are computed
 * relative to "now" at module load so the dashboard's "follow-ups due" / "overdue"
 * indicators are always meaningful. Shapes match the canonical OS entity types.
 */
import type {
  Client,
  CrmNote,
  FollowUp,
  Lead,
  Payment,
  Proposal,
  Task,
} from "@/lib/crm/types";

const NOW = Date.now();
const DAY = 86_400_000;
/** ISO timestamp offset from now by `days` (negative = past). */
const iso = (days: number): string => new Date(NOW + days * DAY).toISOString();
/** Date-only (YYYY-MM-DD) offset from now by `days`. */
const date = (days: number): string => iso(days).slice(0, 10);

const OWNER = "itsallethan@gmail.com";

/* --------------------------------- Clients -------------------------------- */
export const demoClients: Client[] = [
  {
    id: "cl_blackgate",
    name: "Blackgate Studios",
    company: "Blackgate Studios LLC",
    email: "ops@blackgatestudios.com",
    status: "active",
    notes: "Retainer — brand systems + web. Primary contact prefers email.",
    stage: "project_work",
    lead_id: "ld_blackgate",
    won_at: iso(-120),
    created_at: iso(-130),
    updated_at: iso(-3),
  },
  {
    id: "cl_solea",
    name: "Solea Nails",
    company: "Solea Nails & Spa",
    email: "hello@soleanails.com",
    status: "active",
    notes: "Booking site + automation. Monthly maintenance.",
    stage: "revenue",
    lead_id: null,
    won_at: iso(-64),
    created_at: iso(-70),
    updated_at: iso(-8),
  },
  {
    id: "cl_northwind",
    name: "Northwind Logistics",
    company: "Northwind Logistics Inc.",
    email: "it@northwind.example",
    status: "prospect",
    notes: "Evaluating an internal ops dashboard. Budget mid-tier.",
    stage: "active",
    lead_id: "ld_northwind",
    won_at: null,
    created_at: iso(-22),
    updated_at: iso(-2),
  },
  {
    id: "cl_aria",
    name: "Aria Wellness",
    company: "Aria Wellness Co.",
    email: "team@ariawellness.example",
    status: "inactive",
    notes: "Completed one project in Q1. Re-engage in fall.",
    stage: "review",
    lead_id: null,
    won_at: iso(-150),
    created_at: iso(-160),
    updated_at: iso(-40),
  },
];

/* ---------------------------------- Leads --------------------------------- */
export const demoLeads: Lead[] = [
  {
    id: "ld_brightpath",
    name: "Brightpath Dental",
    company: "Brightpath Dental Group",
    email: "owner@brightpath.example",
    phone: "+1 415 555 0142",
    source: "referral",
    status: "contacted",
    notes: "Wants a new patient-intake site. Referred by Solea.",
    follow_up_date: date(1),
    priority: 2,
    owner: OWNER,
    converted_client_id: null,
    last_contacted_at: iso(-4),
    estimated_value: 6500,
    created_at: iso(-12),
    updated_at: iso(-4),
  },
  {
    id: "ld_northwind",
    name: "Marcus Reed",
    company: "Northwind Logistics Inc.",
    email: "it@northwind.example",
    phone: null,
    source: "website",
    status: "proposal",
    notes: "Sent proposal for ops dashboard. Awaiting sign-off.",
    follow_up_date: date(-1),
    priority: 3,
    owner: OWNER,
    converted_client_id: null,
    last_contacted_at: iso(-6),
    estimated_value: 14000,
    created_at: iso(-22),
    updated_at: iso(-6),
  },
  {
    id: "ld_lumen",
    name: "Lumen Coffee",
    company: "Lumen Coffee Roasters",
    email: "hi@lumencoffee.example",
    phone: null,
    source: "instagram",
    status: "new",
    notes: "Inbound DM — interested in e-commerce + loyalty.",
    follow_up_date: date(3),
    priority: 1,
    owner: OWNER,
    converted_client_id: null,
    last_contacted_at: null,
    estimated_value: 4200,
    created_at: iso(-2),
    updated_at: iso(-2),
  },
  {
    id: "ld_blackgate",
    name: "Blackgate Studios",
    company: "Blackgate Studios LLC",
    email: "ops@blackgatestudios.com",
    source: "referral",
    phone: null,
    status: "won",
    notes: "Converted to retainer client.",
    follow_up_date: null,
    priority: 2,
    owner: OWNER,
    converted_client_id: "cl_blackgate",
    last_contacted_at: iso(-121),
    estimated_value: 9000,
    created_at: iso(-140),
    updated_at: iso(-120),
  },
  {
    id: "ld_oldoak",
    name: "Old Oak Realty",
    company: "Old Oak Realty",
    email: null,
    phone: "+1 408 555 0199",
    source: "cold-outreach",
    status: "lost",
    notes: "Went with an in-house option.",
    follow_up_date: null,
    priority: 0,
    owner: OWNER,
    converted_client_id: null,
    last_contacted_at: iso(-30),
    estimated_value: 3000,
    created_at: iso(-45),
    updated_at: iso(-30),
  },
];

/* ---------------------------------- Tasks --------------------------------- */
export const demoTasks: Task[] = [
  {
    id: "tk_nw_proposal",
    client_id: "cl_northwind",
    lead_id: "ld_northwind",
    title: "Follow up on Northwind proposal sign-off",
    status: "open",
    priority: 3,
    priority_level: "high",
    due_date: date(-1),
    notes: "Call Marcus; offer a short walkthrough.",
    owner: OWNER,
    created_at: iso(-6),
    updated_at: iso(-1),
  },
  {
    id: "tk_solea_maint",
    client_id: "cl_solea",
    lead_id: null,
    title: "Monthly maintenance — Solea booking site",
    status: "open",
    priority: 1,
    priority_level: "medium",
    due_date: date(4),
    notes: null,
    owner: OWNER,
    created_at: iso(-3),
    updated_at: iso(-3),
  },
  {
    id: "tk_bg_brand",
    client_id: "cl_blackgate",
    lead_id: null,
    title: "Deliver brand system v2 components",
    status: "in_progress",
    priority: 2,
    priority_level: "high",
    due_date: date(2),
    notes: "Buttons + cards remaining.",
    owner: OWNER,
    created_at: iso(-9),
    updated_at: iso(-1),
  },
  {
    id: "tk_lumen_intro",
    client_id: null,
    lead_id: "ld_lumen",
    title: "Send intro + discovery questions to Lumen",
    status: "done",
    priority: 1,
    priority_level: "low",
    due_date: date(-2),
    notes: "Sent via Instagram.",
    owner: OWNER,
    created_at: iso(-2),
    updated_at: iso(-1),
  },
];

/* ------------------------------- Follow-ups ------------------------------- */
export const demoFollowUps: FollowUp[] = [
  {
    id: "fu_northwind",
    client_id: "cl_northwind",
    lead_id: "ld_northwind",
    title: "Check decision on ops dashboard",
    due_date: date(-1),
    status: "pending",
    notes: "Overdue — proposal sent 6 days ago.",
    owner: OWNER,
    channel: "call",
    created_at: iso(-6),
    updated_at: iso(-6),
  },
  {
    id: "fu_brightpath",
    client_id: null,
    lead_id: "ld_brightpath",
    title: "Send Brightpath a scope summary",
    due_date: date(1),
    status: "pending",
    notes: null,
    owner: OWNER,
    channel: "email",
    created_at: iso(-4),
    updated_at: iso(-4),
  },
  {
    id: "fu_aria",
    client_id: "cl_aria",
    lead_id: null,
    title: "Re-engage Aria Wellness for fall project",
    due_date: date(30),
    status: "pending",
    notes: "Seasonal.",
    owner: OWNER,
    channel: "email",
    created_at: iso(-40),
    updated_at: iso(-40),
  },
];

/* ------------------------------ Proposals --------------------------------- */
export const demoProposals: Proposal[] = [
  {
    id: "pr_northwind",
    client_id: "cl_northwind",
    lead_id: "ld_northwind",
    project_id: null,
    title: "Northwind Ops Dashboard — build + 3mo support",
    amount: 14000,
    currency: "USD",
    status: "sent",
    valid_until: date(9),
    sent_at: iso(-6),
    accepted_at: null,
    notes: "Phase 1 fixed, phase 2 hourly.",
    created_at: iso(-6),
    updated_at: iso(-6),
  },
  {
    id: "pr_brightpath",
    client_id: null,
    lead_id: "ld_brightpath",
    project_id: null,
    title: "Brightpath patient-intake site",
    amount: 6500,
    currency: "USD",
    status: "draft",
    valid_until: date(14),
    sent_at: null,
    accepted_at: null,
    notes: "Awaiting final scope from Brightpath.",
    created_at: iso(-3),
    updated_at: iso(-3),
  },
  {
    id: "pr_blackgate",
    client_id: "cl_blackgate",
    lead_id: "ld_blackgate",
    project_id: null,
    title: "Blackgate brand system + web retainer",
    amount: 9000,
    currency: "USD",
    status: "accepted",
    valid_until: date(-90),
    sent_at: iso(-125),
    accepted_at: iso(-120),
    notes: "Converted to retainer.",
    created_at: iso(-128),
    updated_at: iso(-120),
  },
];

/* --------------------------- Revenue / Payments --------------------------- */
export const demoPayments: Payment[] = [
  {
    id: "pay_bg_1",
    client_id: "cl_blackgate",
    label: "Blackgate retainer — month 4",
    amount: 3000,
    currency: "USD",
    status: "received",
    recorded_date: date(-3),
    invoice_id: null,
    notes: null,
    created_at: iso(-3),
    updated_at: iso(-3),
  },
  {
    id: "pay_solea_1",
    client_id: "cl_solea",
    label: "Solea maintenance + hosting",
    amount: 850,
    currency: "USD",
    status: "received",
    recorded_date: date(-8),
    invoice_id: null,
    notes: null,
    created_at: iso(-8),
    updated_at: iso(-8),
  },
  {
    id: "pay_bg_deposit",
    client_id: "cl_blackgate",
    label: "Blackgate brand system — deposit",
    amount: 4500,
    currency: "USD",
    status: "received",
    recorded_date: date(-118),
    invoice_id: null,
    notes: null,
    created_at: iso(-118),
    updated_at: iso(-118),
  },
  {
    id: "pay_nw_pending",
    client_id: "cl_northwind",
    label: "Northwind dashboard — phase 1 (pending)",
    amount: 7000,
    currency: "USD",
    status: "pending",
    recorded_date: null,
    invoice_id: null,
    notes: "Invoices on acceptance.",
    created_at: iso(-6),
    updated_at: iso(-6),
  },
];

/* ----------------------------------- Notes -------------------------------- */
export const demoNotes: CrmNote[] = [
  {
    id: "nt_nw_1",
    client_id: "cl_northwind",
    lead_id: "ld_northwind",
    body: "Marcus wants role-based access in the dashboard. Flag for scope.",
    owner: OWNER,
    created_at: iso(-6),
    updated_at: iso(-6),
  },
  {
    id: "nt_solea_1",
    client_id: "cl_solea",
    lead_id: null,
    body: "Solea added gift-card sales — revisit automation next month.",
    owner: OWNER,
    created_at: iso(-8),
    updated_at: iso(-8),
  },
  {
    id: "nt_brightpath_1",
    client_id: null,
    lead_id: "ld_brightpath",
    body: "Referred by Solea's owner. Warm intro — move quickly.",
    owner: OWNER,
    created_at: iso(-12),
    updated_at: iso(-12),
  },
];
